name: dgl071
channels:
  - rdkit
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py37h7deecbd_0
  - brotli-python=1.0.9=py37hd23a5d3_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.0=py37h7f8727e_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cudatoolkit=11.6.0=hecad31d_10
  - dgl-cuda11.0=0.7.1=py37_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - icu=58.2=he6710b0_3
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.1=py37h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.4=hcbfbd50_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h780b84a_0
  - openssl=1.0.2u=h7b6447c_0
  - packaging=22.0=py37h06a4308_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h295c915_0
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - py-boost=1.73.0=py37h51133e4_12
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py37h06a4308_0
  - rdkit=2020.09.1.0=py37hd50e099_1
  - readline=7.0=h7b6447c_5
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=1.23=py37_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - cloudpickle==2.2.1
    - conda-pack==0.7.1
    - future==0.18.3
    - hyperopt==0.2.7
    - py4j==0.10.9.7
    - tqdm==4.66.1
prefix: /home/zhenxingwu/miniconda3/envs/dgl071
